-- PostgreSQL / Supabase schema for College Event Booking System.
-- Running this file resets the public tables and their sample data.
DROP TABLE IF EXISTS bookings, events, venues, departments, admins, users CASCADE;

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE admins (
  admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE departments (
  dept_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR(100) NOT NULL
);

CREATE TABLE venues (
  venue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name VARCHAR(100) NOT NULL,
  location VARCHAR(150) NOT NULL,
  capacity INTEGER NOT NULL
);

CREATE TABLE events (
  event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name VARCHAR(150) NOT NULL,
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  total_seats INTEGER NOT NULL,
  available_seats INTEGER NOT NULL,
  venue_id INTEGER NOT NULL REFERENCES venues(venue_id) ON DELETE CASCADE,
  dept_id INTEGER NOT NULL REFERENCES departments(dept_id) ON DELETE CASCADE
);

CREATE TABLE bookings (
  booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  event_id INTEGER NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  seats_booked INTEGER NOT NULL,
  booking_date DATE NOT NULL,
  event_date DATE NOT NULL,
  event_time TIME NOT NULL
);

INSERT INTO departments (dept_id, dept_name) VALUES
  (1, 'CSE'), (2, 'ISE'), (3, 'ECE'), (4, 'EEE'), (5, 'Mechanical'),
  (6, 'Civil'), (7, 'AI & ML');

INSERT INTO venues (venue_id, venue_name, location, capacity) VALUES
  (1, 'DES Seminar Hall 1', 'DES Block', 150),
  (2, 'DES Seminar Hall 2', 'DES Block', 150),
  (3, 'ESB Seminar Hall 1', 'ESB Block', 120),
  (4, 'ESB Seminar Hall 2', 'ESB Block', 120),
  (5, 'Apex Auditorium', 'Main Campus', 500);

INSERT INTO events (event_id, event_name, event_date, event_time, total_seats, available_seats, dept_id, venue_id) VALUES
  (1, 'IEEE Student Branch Orientation', '2026-06-15', '10:00:00', 150, 150, 3, 1),
  (2, 'Introduction to Competitive Programming', '2026-06-18', '02:00:00', 120, 120, 1, 3),
  (3, 'AI & Machine Learning Workshop', '2026-06-22', '09:30:00', 120, 120, 7, 4),
  (4, 'Cyber Security Awareness Seminar', '2026-06-25', '11:00:00', 150, 150, 1, 2),
  (5, 'Robotics and Automation Expo', '2026-06-28', '10:00:00', 300, 300, 3, 5),
  (6, 'Google Developer Student Clubs Orientation', '2026-07-02', '02:00:00', 150, 150, 1, 1),
  (7, 'Placement Readiness Program', '2026-07-05', '09:00:00', 250, 250, 1, 5),
  (8, 'Startup and Entrepreneurship Meetup', '2026-07-08', '01:30:00', 120, 120, 2, 2),
  (9, 'Circuit Design Workshop', '2026-07-12', '10:00:00', 100, 100, 4, 3),
  (10, 'Civil Engineering Innovations Seminar', '2026-07-15', '11:00:00', 120, 120, 6, 4),
  (11, 'EV Technology and Future Mobility Talk', '2026-07-18', '02:00:00', 120, 120, 5, 2),
  (12, 'Data Science Bootcamp', '2026-07-20', '09:30:00', 150, 150, 7, 1),
  (13, 'Women in Engineering Session', '2026-07-22', '11:00:00', 120, 120, 3, 3),
  (14, 'Cloud Computing Workshop', '2026-07-25', '10:00:00', 120, 120, 4, 4),
  (15, 'Annual Technical Fest Inauguration', '2026-08-01', '09:00:00', 500, 500, 1, 5);

INSERT INTO admins (admin_id, username, password) VALUES
  (1, 'admin', '$2a$10$2du6W9NKWNEZAnRTxove/ePFhB6DIdBK.pcodAjReuJMp81sCoUOO');

SELECT setval(pg_get_serial_sequence('departments', 'dept_id'), (SELECT MAX(dept_id) FROM departments));
SELECT setval(pg_get_serial_sequence('venues', 'venue_id'), (SELECT MAX(venue_id) FROM venues));
SELECT setval(pg_get_serial_sequence('events', 'event_id'), (SELECT MAX(event_id) FROM events));
SELECT setval(pg_get_serial_sequence('admins', 'admin_id'), (SELECT MAX(admin_id) FROM admins));
